# Generated by Django 5.0.6 on 2024-06-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lecture_body', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_languages', to='api.language')),
                ('topic', models.ManyToManyField(related_name='lecture_topics', to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_languages', to='api.language')),
                ('topic', models.ManyToManyField(related_name='practice_topics', to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='PairingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.IntegerField()),
                ('description', models.TextField()),
                ('column_a', models.TextField()),
                ('column_b', models.TextField()),
                ('association', models.CharField(max_length=255)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_practices', to='api.practice')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.IntegerField()),
                ('description', models.TextField()),
                ('media_type', models.CharField(max_length=255)),
                ('media_location', models.CharField(max_length=255)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excercices_practices', to='api.practice')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.IntegerField()),
                ('question', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_practices', to='api.practice')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_selections', to='api.selectionexercise')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.IntegerField()),
                ('sentence_complete', models.TextField()),
                ('sentence_incomplete', models.TextField()),
                ('missing_words', models.TextField()),
                ('pratice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_practices', to='api.practice')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.BinaryField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tf_practices', to='api.practice')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('user_rate', models.FloatField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_practices', to='api.practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_users', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_users', to='api.user'),
        ),
        migrations.CreateModel(
            name='LectureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('user_rate', models.FloatField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lr_lectures', to='api.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lr_users', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_users', to='api.user'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
    ]
